### ISSUE TITLE
Projo marqué esquivé alors qu'en fait non

### ISSUE THREAD

**Issue by zorun** [erk3/sciz#104]
Salut, merci pour ce chouette outil !

Il a par contre l'air d'avoir un peu de mal avec les projos, ça me marque parfois "esquivé" alors que c'est un critique, cf. screenshot.

![Screenshot](https://files.polyno.me/tmp/mh-projo-esquive2.png)

Curieusement, ça le fait pas à chaque fois, en voici 2 qui merdent :

- 13/05/2018 à 10:04:25
- 11/05/2018 à 14:35:26

**Comment by erk3** [comment]
A priori juste un problème d'affichage dans la webapp, sera corrigé ASAP.
