### ISSUE TITLE
Faire une page d'accueil différente quand on est connecté

### ISSUE THREAD

**Issue by zorun** [erk3/sciz#105]
J'ai l'impression que la page d'accueil est la même qu'on soit connecté ou non.

Notamment, il est encore marqué qu'on peut forwarder des mails à l'adresse de test, alors que c'est pas celle-ci qu'il faut utiliser quand on est dans un groupe...

À la place, on pourrait par exemple imaginer mettre la liste des groupes dont on fait partie !

**Comment by erk3** [comment]
Message pour les groupes de test va être supprimé et une redirection auto au login sur la page des évènements.
