### ISSUE TITLE
Problème de renvoi de mail (SPF)

### ISSUE THREAD

**Issue by zorun** [erk3/sciz#107]
MH a un enregistrement SPF très strict, qui n'autorise que leur IP à envoyer des mails avec un sender MH.

Ce qu'il faut bien comprendre, c'est que [SPF](http://www.openspf.org/Introduction) protège le "envelope sender" et pas du tout l'adresse qui est dans le `From:`.

Du coup, selon la façon dont la redirection de mail est faite par le client, ça va marcher ou non.  Par exemple, si je fais la redirection dans Sieve sur mon serveur mail, ça ne marche pas (parce qu'il garde l'envelope sender originel), alors que si je bounce le mail depuis mon client ça marche.

Bref, pour éviter les ennuis, il y a une solution très simple : désactiver la vérification SPF sur le serveur mail de SCIZ :)

**Comment by erk3** [comment]
Cela concerne plus la configuration du serveur mail de l'instance officielle de SCIZ que le projet en lui même et tel qu'il est hébergé sur github à date. Nous effectuons désormais du whitelisting pour les MTA qui conservent l'enveloppe d'origine, ceci sur demande. Nous contacter sur la room Miaou officielle pour une demande d'ajout éventuelle.
