### ISSUE TITLE
Support Baroufle

### ISSUE THREAD

**Issue by erk3** [erk3/sciz#126]

**Comment by Glandos** [comment]
Est-ce que ça serait intéressant si je fournissais des messages du Bot de résultat de Baroufle ?

**Comment by erk3** [comment]
Hello

Merci pour ton intérêt pour SCIZ, j'ai déjà collecté plein d'exemples, je n'aurai pas besoin de plus.

La nouvelle version ne va pas tarder à sortir, Baroufle ne sera ps tout de suite pris en compte mais ça suivra sous peu.

L'ensemble des tickets ouverts vont être fermés et remis aux goûts du jour à ce moment.

++
